# Connexion à la base source (prod)
source_db:
  host: "localhost"
  database: "prod"
  user: "user"
  password: "password"

# Connexion au DWH (dev)
dwh_db:
  host: "localhost"
  database: "dwh"
  user: "user"
  password: "password"

# Paramètres par défaut
defaults:
  tolerance: 0
